-- Add new columns to existing comments table
-- We use IF NOT EXISTS to avoid errors if columns are already there
ALTER TABLE public.comments 
ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS parent_id bigint REFERENCES public.comments(id),
ADD COLUMN IF NOT EXISTS likes integer DEFAULT 0;

-- Create comment_likes table for tracking user likes
CREATE TABLE IF NOT EXISTS public.comment_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    comment_id bigint REFERENCES public.comments(id) ON DELETE CASCADE NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, comment_id)
);

-- Enable RLS for comment_likes
ALTER TABLE public.comment_likes ENABLE ROW LEVEL SECURITY;

-- Policies for comment_likes
CREATE POLICY "Users can view all likes" 
    ON public.comment_likes FOR SELECT 
    USING (true);

CREATE POLICY "Users can like comments" 
    ON public.comment_likes FOR INSERT 
    TO authenticated 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can unlike comments" 
    ON public.comment_likes FOR DELETE 
    TO authenticated 
    USING (auth.uid() = user_id);

-- Create a secure function for toggling likes
-- This handles the logic: if liked -> unlike (-1), if not liked -> like (+1)
CREATE OR REPLACE FUNCTION toggle_like(comment_id_param bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id uuid;
  v_liked boolean;
BEGIN
  v_user_id := auth.uid();
  
  -- Check if user already liked
  SELECT EXISTS (
    SELECT 1 FROM public.comment_likes 
    WHERE user_id = v_user_id AND comment_id = comment_id_param
  ) INTO v_liked;
  
  IF v_liked THEN
    -- Unlike: remove record and decrement count
    DELETE FROM public.comment_likes 
    WHERE user_id = v_user_id AND comment_id = comment_id_param;
    
    UPDATE public.comments 
    SET likes = COALESCE(likes, 0) - 1 
    WHERE id = comment_id_param;
  ELSE
    -- Like: insert record and increment count
    INSERT INTO public.comment_likes (user_id, comment_id)
    VALUES (v_user_id, comment_id_param);
    
    UPDATE public.comments 
    SET likes = COALESCE(likes, 0) + 1 
    WHERE id = comment_id_param;
  END IF;
END;
$$;
