-- 1. Create page_likes table
CREATE TABLE IF NOT EXISTS public.page_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id text NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    avatar_url text,
    nickname text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(page_id, user_id)
);

-- 2. Enable RLS
ALTER TABLE public.page_likes ENABLE ROW LEVEL SECURITY;

-- 3. Create policies
CREATE POLICY "Anyone can view likes" 
    ON public.page_likes FOR SELECT 
    USING (true);

CREATE POLICY "Authenticated users can insert likes" 
    ON public.page_likes FOR INSERT 
    TO authenticated 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own likes" 
    ON public.page_likes FOR DELETE 
    TO authenticated 
    USING (auth.uid() = user_id);
