-- Create comments table
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    avatar TEXT,
    email VARCHAR(255),
    phone VARCHAR(50),
    parent_id BIGINT REFERENCES comments(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON comments(parent_id);

-- Grant permissions
GRANT SELECT, INSERT ON comments TO anon;
GRANT ALL ON comments TO authenticated;

-- Create Policies
-- Allow anyone to read comments
CREATE POLICY "Enable read access for all users" ON comments
    FOR SELECT USING (true);

-- Allow anyone to insert comments (since we don't have auth yet, we allow anon inserts)
CREATE POLICY "Enable insert access for all users" ON comments
    FOR INSERT WITH CHECK (true);

-- Allow admins (authenticated) to delete comments
CREATE POLICY "Enable delete for authenticated users only" ON comments
    FOR DELETE USING (auth.role() = 'authenticated');
