name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: kejin-lab-web/package-lock.json

      - run: npm ci
        working-directory: kejin-lab-web
      
      - run: npm run build
        working-directory: kejin-lab-web

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: kejin-lab-web/dist
          branch: gh-pages # The branch the action should deploy to.
